import type { Locale } from "./i18n";

export const financingCopy = {
  en: {
    calculator: "Payment calculator",
    finance: "Finance",
    cash: "Cash",
    vehiclePrice: "Vehicle price",
    cashPrice: "Cash price",
    cashHelp: "Contact our team to confirm the final purchase total.",
    excludedFees: "Excludes taxes, registration and document fees.",
    downPayment: "Down payment",
    downPaymentSlider: "Down payment slider",
    downPaymentHelp: "$250 slider increments; you can enter an exact amount.",
    downPaymentError:
      "Enter a down payment from $0 to the vehicle price, with no more than two decimal places.",
    loanTerm: "Loan term",
    months: "months",
    creditTier: "Estimated credit score",
    creditHelp:
      "Choose a range to see your estimate. This does not check your credit.",
    credit: {
      excellent: "Excellent",
      very_good: "Very good",
      good: "Good",
      consultation: "Let’s talk",
    },
    lowScore: "619 or below",
    chooseCredit: "Choose your credit range to see an estimated payment.",
    loading: "Loading available rates…",
    manualReview: "Financing consultation",
    manualReviewHelp:
      "Leave your contact details below. Our team will discuss financing options with you.",
    ratesUnavailable: "An online rate is not available for this selection.",
    ratesUnavailableHelp:
      "You can still ask our team about financing for this vehicle.",
    monthlyPayment: "Estimated monthly payment",
    perMonth: "/ month",
    apr: "APR",
    estimateNotice: "Estimate only. Actual terms depend on lender approval.",
    illustrativeNotice:
      "Uses preset illustrative rates. This estimate is not a loan offer.",
    details: "Calculation details",
    principal: "Amount financed",
    totalInterest: "Estimated total interest",
    inquiry: "Ask about financing",
    inquiryTitle: "Talk with our team",
    inquiryHelp:
      "Your selections are included with your message. Sending this form does not submit a credit application.",
    selectionRequired:
      "Choose a credit range and enter a valid down payment before sending your inquiry.",
    contactRequired:
      "Enter a phone number or email address so we can reach you.",
    contactHint: "Please include a phone number or email address.",
    nameRequired: "Enter your name (at least two characters).",
    emailInvalid: "Enter a valid email address.",
    submit: "Submit financing inquiry",
    received: "Financing inquiry received.",
    thanks:
      "Our team will contact you to discuss your vehicle and financing selections.",
    another: "Send another inquiry",
    selectionSummary: "Your financing selections",
    messagePlaceholder: "Tell us about your financing needs or ask a question.",
  },
  zh: {
    calculator: "购车付款计算器",
    finance: "贷款",
    cash: "全款",
    vehiclePrice: "车辆售价",
    cashPrice: "全款车价",
    cashHelp: "请联系团队确认最终购车总额。",
    excludedFees: "不包含税金、上牌费及文件费。",
    downPayment: "首付",
    downPaymentSlider: "首付滑块",
    downPaymentHelp: "滑块每次调整 $250，也可以直接输入准确金额。",
    downPaymentError: "请输入 $0 至车辆售价之间的首付，最多保留两位小数。",
    loanTerm: "贷款期限",
    months: "个月",
    creditTier: "预估信用分数",
    creditHelp: "选择分数范围后查看估算，此操作不会查询您的信用。",
    credit: {
      excellent: "优秀",
      very_good: "很好",
      good: "良好",
      consultation: "人工咨询",
    },
    lowScore: "619 及以下",
    chooseCredit: "请选择信用分数范围，查看预估月供。",
    loading: "正在加载可用利率…",
    manualReview: "贷款人工咨询",
    manualReviewHelp: "请在下方留下联系方式，团队会与您沟通贷款选择。",
    ratesUnavailable: "此选择暂时没有可用的线上利率。",
    ratesUnavailableHelp: "您仍然可以向团队咨询这辆车的贷款方案。",
    monthlyPayment: "预估月供",
    perMonth: "/ 月",
    apr: "年利率 APR",
    estimateNotice: "结果仅供估算，实际贷款条件以贷款机构审批为准。",
    illustrativeNotice: "使用预设估算利率，此估算并非贷款报价。",
    details: "计算明细",
    principal: "贷款本金",
    totalInterest: "预估总利息",
    inquiry: "咨询贷款方案",
    inquiryTitle: "联系团队",
    inquiryHelp: "您选择的贷款信息将随留言发送，提交此表格不会发起信用申请。",
    selectionRequired: "请先选择信用分数范围，并输入有效首付，再发送咨询。",
    contactRequired: "请至少填写电话号码或电子邮箱，方便我们联系您。",
    contactHint: "电话号码与电子邮箱至少填写一项。",
    nameRequired: "请输入姓名（至少两个字符）。",
    emailInvalid: "请输入有效的电子邮箱地址。",
    submit: "发送贷款咨询",
    received: "已收到贷款咨询。",
    thanks: "团队会联系您，沟通所选车辆及贷款方案。",
    another: "再次发送咨询",
    selectionSummary: "您选择的贷款信息",
    messagePlaceholder: "告诉我们您的贷款需求，或留下您的问题。",
  },
};

export function financingMoney(
  cents: number,
  locale: Locale = "en",
  decimals = true,
) {
  return new Intl.NumberFormat(locale === "zh" ? "zh-CN" : "en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: decimals ? 2 : 0,
    maximumFractionDigits: 2,
  }).format(cents / 100);
}
